id: P000803
initial_creation_type: ocr
created_at: 31/03/2021
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN22346
  title: ཏུན་ཧོང་ཡིག་ཚང་ཁྲོད་ཀྱི་ས་ལུ་ལྗང་པ་དང་རྡོ་རྗེ་གཅོད་པའི་མཆན་འགྲེལ།
  volumes:
    f3740086f34544b2a18f8f23a95c3ee5:
      image_group_id: I4CN10111
      title: ''
      base_file: v001.txt
  author: ''
